version: "3"
services:

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/order_redis.env
    ports:
    - 5000:5000

  order-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: 0

  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5002 app:app
    env_file:
      - env/stock_redis.env
    ports:
      - 5002:5002

  stock-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build: ./payment
    image: user:latest
    command: gunicorn -b 0.0.0.0:5001 app:app
    env_file:
      - env/payment_redis.env
    ports:
      - 5001:5001

  payment-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: 0
