version: "3"
services:

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"

  order-service:
    build:
      context: ./
      dockerfile: ./order/Dockerfile
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: gunicorn -b 0.0.0.0:5000 app:app
    env_file:
      - env/order_service.env
    ports:
    - "5000:5000"

  order-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: 0
    ports:
      - 5433:5433
    command: -p 5433

  order-db-2:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: 0
    ports:
      - 5434:5434
    command: -p 5434

  order-db-3:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: 0
    ports:
      - 5435:5435
    command: -p 5435

  # stock-service:
  #   build:
  #     context: ./
  #     dockerfile: ./stock/Dockerfile
  #   image: stock:latest
  #   command: gunicorn -b 0.0.0.0:5002 app:app
  #   env_file:
  #     - env/stock_service.env
  #   ports:
  #     - "5002:5002"

  # stock-db:
  #   image: postgres
  #   command: postgres --max_prepared_transactions=100
  #   environment:
  #     POSTGRES_PASSWORD: test123
  #     POSTGRES_DB: 0

  # payment-service:
  #   build:
  #     context: ./
  #     dockerfile: ./payment/Dockerfile
  #   image: user:latest
  #   command: gunicorn -b 0.0.0.0:5001 app:app
  #   env_file:
  #     - env/payment_service.env
  #   ports:
  #     - "5001:5001"

  # payment-db:
  #   image: postgres
  #   command: postgres --max_prepared_transactions=100
  #   environment:
  #     POSTGRES_PASSWORD: test123
  #     POSTGRES_DB: 0

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "22181:2181"

  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "29092:29092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
