apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  selector:
    component: order
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: order-pod-0
  labels:
    component: order
spec:
    containers:
      - name: order
        image: bobdetest123/orderserivce:order2
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "1"
        command: ["gunicorn"]
        args: ["-b", "0.0.0.0:5000", "app:app"]
        ports:
          - containerPort: 5000
        env:
          - name: POSTGRES_HOST_0
            value: order-db-0-postgresql
          - name: POSTGRES_HOST_1
            value: order-db-1-postgresql
          - name: POSTGRES_HOST_2
            value: order-db-2-postgresql
          - name: POSTGRES_PORT_0
            value: "5432"
          - name: POSTGRES_PORT_1
            value: "5432"
          - name: POSTGRES_PORT_2
            value: "5432"
          - name: SERVICE_ID
            value: "0"
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: test123
          - name: POSTGRES_DB
            value: "0"
          - name: GATEWAY_URL
            value: "http://192.168.49.2:80"
          - name: PYTHONUNBUFFERED
            value: 'false'
---
apiVersion: v1
kind: Pod
metadata:
  name: order-pod-1
  labels:
    component: order
spec:
    containers:
      - name: order
        image: bobdetest123/orderserivce:order2
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "1"
        command: ["gunicorn"]
        args: ["-b", "0.0.0.0:5000", "app:app"]
        ports:
          - containerPort: 5000
        env:
          - name: POSTGRES_HOST_0
            value: order-db-0-postgresql
          - name: POSTGRES_HOST_1
            value: order-db-1-postgresql
          - name: POSTGRES_HOST_2
            value: order-db-2-postgresql
          - name: POSTGRES_PORT_0
            value: "5432"
          - name: POSTGRES_PORT_1
            value: "5432"
          - name: POSTGRES_PORT_2
            value: "5432"
          - name: SERVICE_ID
            value: "1"
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: test123
          - name: POSTGRES_DB
            value: "0"
          - name: GATEWAY_URL
            value: "http://192.168.49.2:80"
---
apiVersion: v1
kind: Pod
metadata:
  name: order-pod-2
  labels:
    component: order
spec:
    containers:
      - name: order
        image: bobdetest123/orderserivce:order2
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "1"
        command: ["gunicorn"]
        args: ["-b", "0.0.0.0:5000", "app:app"]
        ports:
          - containerPort: 5000
        env:
          - name: POSTGRES_HOST_0
            value: order-db-0-postgresql
          - name: POSTGRES_HOST_1
            value: order-db-1-postgresql
          - name: POSTGRES_HOST_2
            value: order-db-2-postgresql
          - name: POSTGRES_PORT_0
            value: "5432"
          - name: POSTGRES_PORT_1
            value: "5432"
          - name: POSTGRES_PORT_2
            value: "5432"
          - name: SERVICE_ID
            value: "2"
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: test123
          - name: POSTGRES_DB
            value: "0"
          - name: GATEWAY_URL
            value: "http://192.168.49.2:80"
---
apiVersion: v1
kind: Pod
metadata:
  name: order-pod-3
  labels:
    component: order
spec:
    containers:
      - name: order
        image: bobdetest123/orderserivce:order2
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "1"
        command: ["gunicorn"]
        args: ["-b", "0.0.0.0:5000", "app:app"]
        ports:
          - containerPort: 5000
        env:
          - name: POSTGRES_HOST_0
            value: order-db-0-postgresql
          - name: POSTGRES_HOST_1
            value: order-db-1-postgresql
          - name: POSTGRES_HOST_2
            value: order-db-2-postgresql
          - name: POSTGRES_PORT_0
            value: "5432"
          - name: POSTGRES_PORT_1
            value: "5432"
          - name: POSTGRES_PORT_2
            value: "5432"
          - name: SERVICE_ID
            value: "3"
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: test123
          - name: POSTGRES_DB
            value: "0"
          - name: GATEWAY_URL
            value: "http://192.168.49.2:80"