apiVersion: v1
kind: Service
metadata:
  name: order-service-1
spec:
  type: ClusterIP
  selector:
    component: order
  ports:
    - port: 5001
      name: http
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: order
  template:
    metadata:
      labels:
        component: order
    spec:
      containers:
        - name: order
          image: bobdetest123/orderserivce:order
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5001", "app:app"]
          ports:
            - containerPort: 5001
          env:
            - name: POSTGRES_HOST_0
              value: order-db-0
            - name: POSTGRES_PORT_0
              value: '5101'
            - name: POSTGRES_HOST_1
              value: order-db-1
            - name: POSTGRES_PORT_1
              value: '5102'
            - name: POSTGRES_HOST_2
              value: order-db-2
            - name: POSTGRES_PORT_2
              value: '5103'
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "test123"
            - name: POSTGRES_DB
              value: "0"
            - name: SERVICE_ID
              value: "1"
