apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    component: payment
  ports:
    - port: 6000
      name: http
      targetPort: 6000
---
apiVersion: v1
kind: Pod
metadata:
  name: payment-pod-0
  labels:
    component: payment
spec:
    containers:
      - name: payment
        image: bobdetest123/orderserivce:payment2
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "1Gi"
            cpu: "1"
        command: ["gunicorn"]
        args: ["-b", "0.0.0.0:6000", "app:app"]
        ports:
          - containerPort: 6000
        env:
          - name: POSTGRES_HOST_0
            value: payment-db-0-postgresql
          - name: POSTGRES_PORT_0
            value: "5432"
          - name: POSTGRES_PORT_1
            value: "5432"
          - name: POSTGRES_PORT_2
            value: "5432"
          - name: SERVICE_ID
            value: "0"
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: test123
          - name: POSTGRES_DB
            value: "0"
          - name: PYTHONUNBUFFERED
            value: 'false'
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: payment-pod-1
#  labels:
#    component: payment
#spec:
#    containers:
#      - name: payment
#        image: bobdetest123/orderserivce:payment
#        resources:
#          limits:
#            memory: "1Gi"
#            cpu: "1"
#          requests:
#            memory: "1Gi"
#            cpu: "1"
#        command: ["gunicorn"]
#        args: ["-b", "0.0.0.0:6000", "app:app"]
#        ports:
#          - containerPort: 6000
#        env:
#          - name: POSTGRES_HOST_0
#            value: payment-db-0-postgresql
#          - name: POSTGRES_PORT_0
#            value: "5432"
#          - name: POSTGRES_PORT_1
#            value: "5432"
#          - name: POSTGRES_PORT_2
#            value: "5432"
#          - name: SERVICE_ID
#            value: "1"
#          - name: POSTGRES_USER
#            value: postgres
#          - name: POSTGRES_PASSWORD
#            value: test123
#          - name: POSTGRES_DB
#            value: "0"
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: payment-pod-2
#  labels:
#    component: payment
#spec:
#    containers:
#      - name: payment
#        image: bobdetest123/orderserivce:payment
#        resources:
#          limits:
#            memory: "1Gi"
#            cpu: "1"
#          requests:
#            memory: "1Gi"
#            cpu: "1"
#        command: ["gunicorn"]
#        args: ["-b", "0.0.0.0:6000", "app:app"]
#        ports:
#          - containerPort: 6000
#        env:
#          - name: POSTGRES_HOST_0
#            value: payment-db-0-postgresql
#          - name: POSTGRES_PORT_0
#            value: "5432"
#          - name: POSTGRES_PORT_1
#            value: "5432"
#          - name: POSTGRES_PORT_2
#            value: "5432"
#          - name: SERVICE_ID
#            value: "2"
#          - name: POSTGRES_USER
#            value: postgres
#          - name: POSTGRES_PASSWORD
#            value: test123
#          - name: POSTGRES_DB
#            value: "0"
#---
#apiVersion: v1
#kind: Pod
#metadata:
#  name: payment-pod-3
#  labels:
#    component: payment
#spec:
#    containers:
#      - name: payment
#        image: bobdetest123/orderserivce:payment
#        resources:
#          limits:
#            memory: "1Gi"
#            cpu: "1"
#          requests:
#            memory: "1Gi"
#            cpu: "1"
#        command: ["gunicorn"]
#        args: ["-b", "0.0.0.0:6000", "app:app"]
#        ports:
#          - containerPort: 6000
#        env:
#          - name: POSTGRES_HOST_0
#            value: payment-db-0-postgresql
#          - name: POSTGRES_PORT_0
#            value: "5432"
#          - name: POSTGRES_PORT_1
#            value: "5432"
#          - name: POSTGRES_PORT_2
#            value: "5432"
#          - name: SERVICE_ID
#            value: "3"
#          - name: POSTGRES_USER
#            value: postgres
#          - name: POSTGRES_PASSWORD
#            value: test123
#          - name: POSTGRES_DB
#            value: "0"