apiVersion: v1
kind: Service
metadata:
  name: stock-service
spec:
  type: ClusterIP
  selector:
    component: stock
  ports:
    - port: 5200
      name: http
      targetPort: 5200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: stock
  template:
    metadata:
      labels:
        component: stock
    spec:
      containers:
        - name: stock
          image: iiacoban42/stock:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5200", "app:app"]
          ports:
            - containerPort: 5200
          env:
            - name: POSTGRES_HOST_1
              value: stock-db-1
            - name: POSTGRES_PORT_1
              value: '5201'
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "test123"
            - name: POSTGRES_DB
              value: "0"
