apiVersion: v1
kind: Service
metadata:
  name: user-service-1
spec:
  type: ClusterIP
  selector:
    component: user
  ports:
    - port: 6001
      name: http
      targetPort: 6001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user
  template:
    metadata:
      labels:
        component: user
    spec:
      containers:
        - name: user
          image: bobdetest123/orderserivce:user
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:6001", "app:app"]
          ports:
            - containerPort: 6001
          env:
            - name: POSTGRES_HOST_0
              value: payment-db-0
            - name: POSTGRES_PORT_0
              value: '6101'
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "test123"
            - name: POSTGRES_DB
              value: "0"
            - name: SERVICE_ID
              value: "0"
