apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  selector:
    component: user
  ports:
    - port: 5300
      name: http
      targetPort: 5300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user
  template:
    metadata:
      labels:
        component: user
    spec:
      containers:
        - name: user
          image: iiacoban42/user:latest
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5300", "app:app"]
          ports:
            - containerPort: 5300
          env:
            - name: POSTGRES_HOST_1
              value: payment-db-1
            - name: POSTGRES_PORT_1
              value: '5301'
            - name: POSTGRES_HOST_2
              value: payment-db-2
            - name: POSTGRES_PORT_2
              value: '5302'
            - name: POSTGRES_HOST_3
              value: payment-db-3
            - name: POSTGRES_PORT_3
              value: '5303'
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "test123"
            - name: POSTGRES_DB
              value: "0"
